excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules:
 - no_space_in_method_call
 - multiple_closures_with_trailing_closure
line_length:
  error: 400 
  warning: 300
